server:
  port: 8051
  tomcat:
    max-connections: 10000  # 最大连接数
    threads:
      max: 800              # 最大工作线程数
      min-spare: 100        # 最小空闲线程数
    accept-count: 100       # 等待队列长度
    connection-timeout: 20000

logging:
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
      total-size-cap: 3GB # 日志文件进行滚动和清理

db:
  disableAutoConnect: true

spring:
  servlet:
    multipart: # 文件上传设置
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB # 决定了多大的文件会直接写入内存
  #  main:
  #    lazy-initialization: true
  #  autoconfigure:
  #    exclude:
  #      - org.redisson.spring.starter.RedissonAutoConfigurationV2 # 禁用 Redis
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: creative-martin-46984.upstash.io
    port: 6379
    password: xxxx
    ssl: true
